#!/bin/bash -e

cd ../wifi-setup-material

# Rebuild the distribution.
rm -r dist
ng build --prod

cd -

www=lib/wifi_setup/www

# Move over the rebuilt distribution.
rm -r $www
mv ../wifi-setup-material/dist/wifi-setup $www

before=( $(du -hs $www) )

# Search for files that are at least 1KiB.
for file in $(find $www -type f -size +1k)
do
    gzip --best $file

    # If the gzip makes little difference undo the compression.
    pct=$(gzip --list $file | sed -n 's/.*\s\([0-9.-]\+\)%\s.*/\1/p')
    if (( $(echo "$pct < 5" | bc -l ) ))
    then
        gunzip $file
    fi
done

after=( $(du -hs $www) )

echo "Info: reduced size of www from ${before[0]} to ${after[0]}"
